### ISSUE TITLE
Routing scheduler with two routing specs immediately deadlocks in threaded logger

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#165]
**Describe the bug**
Exactly as title.

**To Reproduce**
1. Creating instance of routingsheduler app
2. assign two or more routing specs
3. start the routing scheduler
4. wait a seconds
5. run jstack on the java pid to see the two routing spec threads stopped in the ThreadedLogger log method.

**Expected behavior**
Log writing properly synchronizes

**Screenshots**
```
"EDL-USGS" #39 prio=5 os_prio=64 tid=0x0000000101fda800 nid=0x4a waiting for monitor entry [0xffffffff5d7ee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at ilex.util.ThreadLogger.log(ThreadLogger.java:141)
        - waiting to lock <0x00000005c03597b0> (a ilex.util.ThreadLogger)
        at ilex.util.Logger.debug3(Logger.java:303)
        at decodes.decoder.DecodedMessage.addSample(DecodedMessage.java:826)
        at decodes.decoder.FieldOperation.execute(FieldOperation.java:356)
        at decodes.decoder.DecodesOperationGroup.execute(DecodesOperationGroup.java:80)
        at decodes.db.FormatStatement.execute(FormatStatement.java:131)
        at decodes.db.DecodesScript.decodeMessage(DecodesScript.java:407)
        - locked <0x000000071b0839d8> (a decodes.db.DecodesScript)
        at decodes.routing.RoutingSpecThread.attemptDecode(RoutingSpecThread.java:707)
        at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:554)

"CWMSv2-DCP-OTF" #38 prio=5 os_prio=64 tid=0x0000000102277800 nid=0x49 runnable [0xffffffff6ddeb000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        - locked <0x00000005c0f8e500> (a java.lang.Object)
        at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:174)
        at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555)
        at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:258)
        at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:190)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:132)
        at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:105)
        at oracle.net.ns.NIONSDataChannel.readDataFromSocketChannel(NIONSDataChannel.java:91)
        at oracle.jdbc.driver.T4CMAREngineNIO.prepareForUnmarshall(T4CMAREngineNIO.java:764)
        at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:429)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:407)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:765)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1362)
        - locked <0x00000005c0d32a50> (a oracle.jdbc.driver.T4CConnection)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:369)
        at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleStatement$$$Proxy.executeQuery(Unknown Source)
        at opendcs.dao.DaoBase.doQuery(DaoBase.java:198)
        at opendcs.dao.DacqEventDAO.<init>(DacqEventDAO.java:37)
        at decodes.sql.SqlDatabaseIO.makeDacqEventDAO(SqlDatabaseIO.java:2397)
        at decodes.routing.DacqEventLogger.writeDacqEvent(DacqEventLogger.java:64)
        at decodes.routing.DacqEventLogger.doLog(DacqEventLogger.java:56)
        at ilex.util.Logger.log(Logger.java:155)
        at ilex.util.ThreadLogger.log(ThreadLogger.java:143)
        - locked <0x00000005c03597b0> (a ilex.util.ThreadLogger)
        at ilex.util.Logger.warning(Logger.java:339)
        at decodes.comp.RatingComputation.apply(RatingComputation.java:184)
        at decodes.comp.ComputationProcessor.applyComputations(ComputationProcessor.java:97)
        - locked <0x00000005c0df4148> (a decodes.comp.ComputationProcessor)
        at decodes.routing.RoutingSpecThread.attemptDecode(RoutingSpecThread.java:732)
        at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:554)

```

**ServerSide (please complete the following information):**
 - OS: Solaris 11/SPARC
 - Version: 7.0.4

**Additional context**
Looking at the code right now I'm honestly baffled as to way. There's no extra mutex locking than just the synchronized marker on the log call, and yet it's still deadlocking for us. I need to verify my test environment to see if I have that active and this is some weird Solaris/SPARC only java issue.

**Comment by MikeNeilson** [comment]
addition portion of stack trace:

```
"main" #1 prio=5 os_prio=64 tid=0x000000010010e800 nid=0x2 waiting for monitor entry [0xffffffff7f2ee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at ilex.util.ThreadLogger.log(ThreadLogger.java:141)
        - waiting to lock <0x00000005c03037c8> (a ilex.util.ThreadLogger)
        at ilex.util.Logger.debug3(Logger.java:303)
        at opendcs.dao.DaoBase.debug3(DaoBase.java:277)
        at opendcs.dao.LoadingAppDao.checkCompProcLock(LoadingAppDao.java:682)
        at decodes.routing.RoutingScheduler.runApp(RoutingScheduler.java:246)
        at decodes.tsdb.TsdbAppTemplate.execute(TsdbAppTemplate.java:249)
        at decodes.routing.RoutingScheduler.main(RoutingScheduler.java:562)

```

Seems like an odd interaction between either the Logger or the DaoBase or both.

**Comment by MikeNeilson** [comment]
Also we limited things to a single routing spec and it's still happened, hence why I added that additional stack trace.

**Comment by MikeNeilson** [comment]
Update: running with even more specs causes other issues.

The deadlock hasn't been reproducible however I think some recent modifications in https://github.com/opendcs/opendcs/pull/254 will have adjusted for that.
