### ISSUE TITLE
Review RoutingScheduler/RoutingSpecThread

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#294]
**Component to be refactored**
RoutingSpecThread

**Purpose of refactoring**
In the effort to get the RoutingScheduler to handle various failures better and reviewing the code, there is a

- shutdown()
- quit()
- and other functions that need to be called. And other variables to set. Some of these variables are publicly access and set from other classes threads.

The checks for failure require several perquisites to trigger restarts that aren't always met depending on the nature of the failure.

**Proposed method**
Move the whole system to be more self contained except for some support for status reporting, probably through some interface that would contain existing functions.

Java, since 1.5, includes a concept of an `ExecutorService and `ScheduledExecutorService`. The RoutingScheduler itself more or less implements similar behavior so it would make sense to either have the RoutingScheduler either implement or use the built in ExecutorService.

RoutingSpecThread should move to implement Runnable instead of extending Thread, in addition to other interfaces required for status reporting.

Additionally, failures that a RoutingSpec can correct, like a DataSource issue should be handled by the routing spec thread internally.

**Additional context**
For scheduled and run once task using the ExecutorService and configurable thread pools will make it easier to balance resources and load. Also while its been difficult I think it makes sense to get the current RoutingScheduler working better before embarking on such a large change.

**Comment by msweier** [comment]
@MikeNeilson per our meeting today, here is my log of when both routing specs failed roughly 11 hrs after they restarted. I have more in the log if you need it and can send via Teams.

`DBG2    11/25/24 19:39:58 Finishing Message: final time = 'Thu Jan 01 00:00:00 GMT 1970', status=0, firstSample = 11/25/2024 19:30:00: 1438
DBG2    11/25/24 19:39:58 No converter from 'FT' to 'VOLT': Attempting to derive one...
DBG1    11/25/24 19:39:58 Cannot find converter for 'ft(feet)' to 'volt(Volts)'
WARNING 11/25/24 19:39:58 Cannot convert samples for time series 'Inst.0.OTHER-GOES-Raw15Minutes,sdi=5984016' from ft to volt -- assuming already correct units.
WARNING 11/25/24 19:41:28 RoutingScheduler Unexpected exception while Checking lock: java.lang.RuntimeException: Error retrieving connection
DBG2    11/25/24 19:41:28 lrgsds-1 DDS Connection (myServer:myPort) Requesting DCP Message Block Ext (timeout=1000)...
WARNING 11/25/24 19:41:28 CwmsConsumer Error storing TS data: java.lang.RuntimeException: Error retrieving connection
WARNING 11/25/24 19:41:28 java.lang.RuntimeException: Error retrieving connection
	at decodes.cwms.CwmsSqlDatabaseIO.getConnection(CwmsSqlDatabaseIO.java:335)
	at opendcs.dao.DaoBase.withConnection(DaoBase.java:390)
	at opendcs.dao.DaoBase.withStatement(DaoBase.java:411)
	at opendcs.dao.DaoBase.doModify(DaoBase.java:520)
	at opendcs.dao.DacqEventDAO.writeEvent(DacqEventDAO.java:97)
	at decodes.routing.DacqEventLogger.writeDacqEvent(DacqEventLogger.java:67)
	at decodes.routing.DacqEventLogger.doLog(DacqEventLogger.java:56)
	at ilex.util.Logger.log(Logger.java:155)
	at ilex.util.ThreadLogger.log(ThreadLogger.java:143)
	at ilex.util.Logger.warning(Logger.java:339)
	at decodes.util.TSUtil.convertUnits(TSUtil.java:96)
	at decodes.cwms.CwmsTimeSeriesDAO.saveTimeSeries(CwmsTimeSeriesDAO.java:746)
	at decodes.cwms.CwmsConsumer.processAndStoreData(CwmsConsumer.java:460)
	at decodes.cwms.CwmsConsumer.startMessage(CwmsConsumer.java:369)
	at decodes.consumer.DumpFormatter.formatMessage(DumpFormatter.java:127)
	at decodes.routing.RoutingSpecThread.formatAndOutputMessage(RoutingSpecThread.java:620)
	at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:575)
Caused by: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.ucp.util.UCPErrorHandler.newSQLException(UCPErrorHandler.java:456)
	at oracle.ucp.util.UCPErrorHandler.throwSQLException(UCPErrorHandler.java:133)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:2004)
	at oracle.ucp.jdbc.PoolDataSourceImpl.access$400(PoolDataSourceImpl.java:201)
	at oracle.ucp.jdbc.PoolDataSourceImpl$31.build(PoolDataSourceImpl.java:4279)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1917)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1880)
	at usace.cwms.db.jooq.util.ConnectionPoolUcp.getNormalConnection_aroundBody12(ConnectionPoolUcp.java:182)
	at usace.cwms.db.jooq.util.ConnectionPoolUcp$AjcClosure13.run(ConnectionPoolUcp.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at usace.cwms.db.aspect.jooq.SQLExceptionWrapperAspect.translateToSQLException(SQLExceptionWrapperAspect.java:51)
	at usace.cwms.db.jooq.util.ConnectionPoolUcp.getNormalConnection(ConnectionPoolUcp.java:160)
	at usace.cwms.db.jooq.util.ConnectionPoolUcp.getConnection_aroundBody28(ConnectionPoolUcp.java:308)
	at usace.cwms.db.jooq.util.ConnectionPoolUcp$AjcClosure29.run(ConnectionPoolUcp.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
	at usace.cwms.db.aspect.jooq.SQLExceptionWrapperAspect.translateToSQLException(SQLExceptionWrapperAspect.java:51)
	at usace.cwms.db.jooq.util.ConnectionPoolUcp.getConnection(ConnectionPoolUcp.java:297)
	at usace.cwms.db.dao.util.connection.CwmsDbConnectionPool.getConnection(CwmsDbConnectionPool.java:251)
	at usace.cwms.db.dao.util.connection.CwmsDbConnectionPool.getConnection(CwmsDbConnectionPool.java:277)
	at decodes.cwms.CwmsConnectionPool.getConnection(CwmsConnectionPool.java:250)
	at decodes.cwms.CwmsSqlDatabaseIO.getConnection(CwmsSqlDatabaseIO.java:331)
	... 16 more
Caused by: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
	at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
	at oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:134)
	at oracle.ucp.common.Database.createPooledConnection(Database.java:256)
	at oracle.ucp.common.Service$2.exec(Service.java:630)
	at oracle.ucp.common.Service$2.exec(Service.java:627)
	at oracle.ucp.actors.InterruptableActor.doAction(InterruptableActor.java:128)
	at oracle.ucp.common.Service.createConnectionInterruptably(Service.java:627)
	at oracle.ucp.common.Service.create(Service.java:807)
	at oracle.ucp.common.Service.create(Service.java:575)
	at oracle.ucp.common.Topology.create(Topology.java:159)
	at oracle.ucp.common.Core.growBorrowed(Core.java:1057)
	at oracle.ucp.common.UniversalConnectionPoolImpl.helpGrowBorrowed(UniversalConnectionPoolImpl.java:301)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionWithoutCountingRequests(UniversalConnectionPoolImpl.java:247)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnectionAndValidate(UniversalConnectionPoolImpl.java:153)
	at oracle.ucp.common.UniversalConnectionPoolImpl.borrowConnection(UniversalConnectionPoolImpl.java:122)
	at oracle.ucp.jdbc.JDBCConnectionPool.borrowConnection(JDBCConnectionPool.java:174)
	at oracle.ucp.jdbc.oracle.OracleJDBCConnectionPool.borrowConnection(OracleJDBCConnectionPool.java:613)
	at oracle.ucp.jdbc.oracle.OracleConnectionConnectionPool.borrowConnection(OracleConnectionConnectionPool.java:103)
	at oracle.ucp.jdbc.PoolDataSourceImpl.getConnection(PoolDataSourceImpl.java:1981)
	... 34 more
Caused by: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:854)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
	at oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:406)
	at oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:291)
	at oracle.jdbc.pool.OracleDataSource$1.build(OracleDataSource.java:1683)
	at oracle.jdbc.pool.OracleDataSource$1.build(OracleDataSource.java:1669)
	at oracle.ucp.jdbc.oracle.OracleDataSourceConnectionFactoryAdapter.createConnection(OracleDataSourceConnectionFactoryAdapter.java:103)
	... 51 more
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:571)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:548)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:682)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:309)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)
	... 59 more
Caused by: java.io.IOException: Connection refused, socket connect lapse 0 ms. /myDb myPort 0 1 true
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:233)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:174)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:510)
	... 64 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:99)
	at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:77)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:192)
	... 66 more

DBG1    11/25/24 19:41:28 Doing up2date checks...
DBG1    11/25/24 19:41:28 decodes.sql.RoutingSpecListIO.setConnection(1376656733)
DBG1    11/25/24 19:41:28 decodes.sql.PresentationGroupListIO.setConnection(1376656733)
DBG1    11/25/24 19:41:28 decodes.sql.NetworkListListIO.setConnection(1376656733)
DBG1    11/25/24 19:41:28 decodes.sql.DataSourceListIO.setConnection(1376656733)
DBG1    11/25/24 19:41:28 decodes.sql.RoutingSpecListIO.setConnection(null)
DBG1    11/25/24 19:41:28 decodes.sql.PresentationGroupListIO.setConnection(null)
DBG1    11/25/24 19:41:28 decodes.sql.NetworkListListIO.setConnection(null)
DBG1    11/25/24 19:41:28 decodes.sql.DataSourceListIO.setConnection(null)
DBG1    11/25/24 19:41:28 RoutingSpec(OTHER-DCP-CON-CWMS) checkNetworkLists: There are 1 explicit lists.
DBG1    11/25/24 19:41:28 RoutingSpec(OTHER-DCP-CON-CWMS) checkNetworkLists: There are 1 explicit list namess.
DBG1    11/25/24 19:41:28 decodes.sql.NetworkListListIO.setConnection(381726428)
DBG1    11/25/24 19:41:28 decodes.sql.NetworkListListIO.setConnection(null)
DBG2    11/25/24 19:41:28 lrgsds-0 DDS Connection (myServer:myPort) Requesting DCP Message Block Ext (timeout=1000)...
DBG1    11/25/24 19:41:29 ScheduleEntryExec shutdown() called for SchedEntry:CEMVP-GOES
INFO    11/25/24 19:41:29 RoutingSpec(CEMVP-DCP-CON-CWMS) shutdown called.
DBG2    11/25/24 19:41:29 lrgsds-1 DDS Connection (myServer:myPort) sendGoodbye()
DBG2    11/25/24 19:41:29 lrgsds-1 DDS Connection (myServer:myPort) Goodbye response OK
DBG2    11/25/24 19:41:29 lrgsds-1 Disconnecting from 'myServer', port myPort
DBG2    11/25/24 19:41:29 BasicClient myServer:myPort disconnect()
DBG1    11/25/24 19:41:29 ScheduleEntryExec shutdown() called for SchedEntry:Recovery_CEMVP
DBG1    11/25/24 19:41:29 ScheduleEntryExec shutdown() called for SchedEntry:SingleRecovery
DBG1    11/25/24 19:41:29 ScheduleEntryExec shutdown() called for SchedEntry:OTHER-GOES
INFO    11/25/24 19:41:29 RoutingSpec(OTHER-DCP-CON-CWMS) shutdown called.
DBG2    11/25/24 19:41:29 lrgsds-0 DDS Connection (myServer:myPort) sendGoodbye()
DBG2    11/25/24 19:41:29 lrgsds-0 DDS Connection (myServer:myPort) Goodbye response OK
DBG2    11/25/24 19:41:29 lrgsds-0 Disconnecting from 'myServer', port myPort
DBG2    11/25/24 19:41:29 BasicClient myServer:myPort disconnect()
DBG1    11/25/24 19:41:29 ScheduleEntryExec shutdown() called for SchedEntry:Recovery_OTHER_GOES
WARNING 11/25/24 19:41:29 RoutingSpec(CEMVP-DCP-CON-CWMS) Unexpected exception in data source 'cemvp-hotbackup': java.lang.NullPointerException
DBG1    11/25/24 19:41:29 ScheduleEntryExecutive.rsFinished() SchedEntry:CEMVP-GOES state is now shutdown
INFO    11/25/24 19:41:29 RoutingSpec(CEMVP-DCP-CON-CWMS) -------------- RoutingSpec 'CEMVP-DCP-CON-CWMS' Terminating --------------
WARNING 11/25/24 19:41:29 RoutingSpec(OTHER-DCP-CON-CWMS) Unexpected exception in data source 'cemvp-hotbackup': java.lang.NullPointerException
DBG1    11/25/24 19:41:30 ScheduleEntryExecutive.rsFinished() SchedEntry:OTHER-GOES state is now shutdown
INFO    11/25/24 19:41:30 RoutingSpec(OTHER-DCP-CON-CWMS) -------------- RoutingSpec 'OTHER-DCP-CON-CWMS' Terminating --------------
DBG1    11/25/24 19:41:34 runApp() exiting.
INFO    11/25/24 19:41:34 Shutting down Decodes Connection.
INFO    11/25/24 19:41:34 Closing  database connection.
INFO    11/25/24 19:41:34 RoutingScheduler exiting.
INFO    11/26/24 08:47:20 Set DecodesSettings source=/myPath/opendcs_user/user.properties
DBG1    11/26/24 08:47:20 Forwarding javax.logging to ilex log.
INFO    11/26/24 08:47:20 After parseArgs, DecodesSettings src file=/myPath/opendcs_user/user.properties
INFO    11/26/24 08:47:20 ===============================================
INFO    11/26/24 08:47:20 RoutingScheduler starting. OPENDCS 7.0.12 built on Feb 20, 2024, pid=32752`

**Comment by MikeNeilson** [comment]
so you're problem is a bit more explainable:
`Caused by: java.sql.SQLException: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection`

System had a network/database hiccup at the moment the connection was requested.

**Comment by msweier** [comment]
> System had a network/database hiccup at the moment the connection was requested.

Hmm...this happened again at a similar time. There weren't any error messages that followed. It just shut 'er down.
`WARNING 12/05/24 20:28:11 RoutingScheduler Unexpected exception while Checking lock: java.lang.RuntimeException: Error retrieving connection
DBG2    12/05/24 20:28:12 lrgsds-5 DDS Connection (myServer:myPort) Requesting DCP Message Block Ext (timeout=1000)...
DBG2    12/05/24 20:28:12 lrgsds-6 DDS Connection (myServer:myPort) Requesting DCP Message Block Ext (timeout=1000)...
DBG1    12/05/24 20:28:12 ScheduleEntryExec shutdown() called for SchedEntry:CEMVP-GOES
INFO    12/05/24 20:28:12 RoutingSpec(CEMVP-DCP-CON-CWMS) shutdown called.`

**Comment by MikeNeilson** [comment]
Odd. any similar messages from the CWMS Server Logs?

Unforunately with an error like that OpenDCS can really only assume the worst and has no way to recover without possibly making it worse for the upstream.

**Comment by msweier** [comment]
Nothing I could find in the logs in the dated folder. I'll let you know if it happens again.
