### ISSUE TITLE
7.0.10-rc1 and current master apps crash on startup for HDB

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#397]
Stack trace for all apps I've tried:

'''dbedit -P ./decodes.properties.rdsuc 
Exception in thread "main" java.lang.ClassCastException: class opendcs.util.sql.WrappedConnection cannot be cast to class oracle.jdbc.OracleConnection (opendcs.util.sql.WrappedConnection and oracle.jdbc.OracleConnection are in unnamed module of loader 'app')
	at decodes.hdb.HdbSqlDatabaseIO.setDBDatetimeFormat(HdbSqlDatabaseIO.java:49)
	at decodes.sql.SqlDatabaseIO.connectToDatabase(SqlDatabaseIO.java:368)
	at decodes.sql.SqlDatabaseIO.<init>(SqlDatabaseIO.java:284)
	at decodes.hdb.HdbSqlDatabaseIO.<init>(HdbSqlDatabaseIO.java:25)
	at decodes.db.DatabaseIO.makeDatabaseIO(DatabaseIO.java:72)
	at lrgs.gui.DecodesInterface.initDecodesMinimal(DecodesInterface.java:207)
	at lrgs.gui.DecodesInterface.initDecodes(DecodesInterface.java:149)
	at decodes.launcher.LauncherFrame.doInitDecodes(LauncherFrame.java:1309)
	at decodes.launcher.LauncherFrame.access$1100(LauncherFrame.java:177)
	at decodes.launcher.LauncherFrame$36.run(LauncherFrame.java:1120)
'''

Linux GUI or command line, all the same

**Comment by agilmore2** [comment]
Using this code in HDBSqlDatabaseIO.java:50 fixes it, but seems fragile if there's many connection threads flying around?
```
		try (OracleConnection ocon = getConnection().unwrap(OracleConnection.class)) {
			ocon.setSessionTimeZone(databaseTimeZone);
		}
```

**Comment by MikeNeilson** [comment]
that should be:

```java
try(Connection conn = getConnection())
{
    OracleConnection ocon = conn.unwrap(OracleConnection.class)
   ...
}
```

or alternatively
```java
try(Connection conn = getConnection()
     PreparedStatement stmt = conn.prepateStatement("ALTER SESSION SET TIME_ZONE = 'GMT'");
)
{
    stmt.execut();
}
```

Otherwise the real connection is going to get closed in that try-with-resource block, quite possibly why #398 is happening.

But yes, going this all with a single connection is rather brittle. But it's part of moving things to a proper Connection Pool. I think we're almost there.
