### ISSUE TITLE
setDecodesUser:   Status message is null instead of the filename

### ISSUE THREAD

**Issue by ktarbet** [opendcs/opendcs#492]
**Describe the bug**

setDecodesUser.bat  (UserAuthFile.java) prints a null instead of the filename.

There are some command line options that don't appear to work, and I haven't found documentation for all the options.

note: the auth file is properly created in this use case shown next.

**To Reproduce**

install OpenDCS 7.0.12 client on windows.

```
C:\bin\OPENDCS\bin>setDecodesUser.bat c:/bin/.decodes.auth
User Name: decodes-user
Password:****
writing to null...
```

**Expected behavior**
should not print 'null'

note: The code in UserAuthFile.java has logic for the following arguments:

* \-filename       (query option; prints user and password inside the file)
* -pfilename     (specify and create file)
* -p filename    (specify and create file)
* filename       (specify and create file)

I'm getting errors when trying the -pfilename or -p filename options 
like this:

```
C:\bin\OPENDCS\bin>setDecodesUser.bat -p c:/bin/.decodes.auth
writing to c:/bin/.decodes.auth...
Exception in thread "main" java.lang.NullPointerException
        at ilex.util.UserAuthFile.write(UserAuthFile.java:141)
        at ilex.util.UserAuthFile.main(UserAuthFile.java:352)
```

**Summary**

Need to decide what options should exist, then refactor and document.

**Comment by MikeNeilson** [comment]
did we fix this?
