### ISSUE TITLE
complock list and showCompDepends - version v7.0.13-RC13

### ISSUE THREAD

**Issue by zamusacelre** [opendcs/opendcs#552]
**Describe the bug**

In version 7.0.13-RC01.  On USACE server.  When run complocklist or showCompDepends getting long list of INFO/WARNINGs that makes the list looks very long relative to what the expected behavior is.

** Bug errors** 
$ complocklist
Apr 15, 2024 7:27:57 PM decodes.tsdb.TsdbAppTemplate startupLogMessage
INFO: ===============================================
Apr 15, 2024 7:27:57 PM decodes.tsdb.TsdbAppTemplate startupLogMessage
INFO: utility starting. OPENDCS 7.0.13-RC01 built on Mar 22, 2024, pid=3412
Init DECODES DB: Apr 15, 2024 7:27:57 PM usace.cwms.db.jooq.util.ConnectionPersi                                         stenceManager <init>
INFO: Connection persistence disabled. To enable set system property cwms.connec                                         tion.persist=true
Apr 15, 2024 7:28:03 PM usace.cwms.db.jooq.AbstractCwmsDbDao testCompatibility_a                                         roundBody0
WARNING: JOOQ CWMSDB API implemented for CWMS database schema version 18.1.21, c                                         onnecting to version 23.3.16
Apr 15, 2024 7:28:03 PM decodes.sql.SqlDatabaseIO readVersionInfo
INFO: Connected to DECODES SQL database version 68
EU, Enum, DataType, Sources,
0 Locks Retrieved:
Apr 15, 2024 7:28:03 PM decodes.sql.SqlDatabaseIO close
INFO: Closing  database connection.
Apr 15, 2024 7:28:03 PM decodes.tsdb.TsdbAppTemplate execute
INFO: utility exiting.
Apr 15, 2024 7:28:03 PM usace.cwms.db.jooq.util.ConnectionPoolUcp shutdownHook_a                                         roundBody2
INFO: Closing all database connections before exiting.

**To Reproduce**
1.On USACE test server
2. run complocklist
3. See output
4. run showCompDepends 
5. and get the following content at the end of the command on the screen: chaning the opendcs.init file 255830430,    "SC10-EmergencySpillway.Flow-Out.Ave.~1Day.1Day.Best-NWO",   1791020,  "NWO-Inflow_Daily",  1323020,  "flowtotal"
Apr 15, 2024 6:34:34 PM decodes.tsdb.TsdbAppTemplate closeDb
INFO: Closing database connection.
java.lang.Exception
        at decodes.tsdb.TsdbAppTemplate.closeDb(TsdbAppTemplate.java:406)
        at decodes.tsdb.TsdbAppTemplate.execute(TsdbAppTemplate.java:183)
        at decodes.tsdb.CompDependsList.main(CompDependsList.java:48)
 
Apr 15, 2024 6:34:34 PM decodes.sql.SqlDatabaseIO close
INFO: Closing  database connection.
Apr 15, 2024 6:34:34 PM decodes.tsdb.TsdbAppTemplate execute
INFO: utility exiting.
Apr 15, 2024 6:34:34 PM usace.cwms.db.jooq.util.ConnectionPoolUcp shutdownHook_aroundBody2
INFO: Closing all database connections before exiting.

**Expected behavior**
for complocklist get a concise list :  List all current computation-processor locks. This will show you which CPs are currently running.
for showCompDepends - This is a trouble-shooting utility to print out the current computation dependencies in a CSV format. 

**Screenshots**

**Desktop/ServerSide (please complete the following information):**
 - USACE server
 - Version 7.0.13-RC01

**Additional context**
Goal of this issue to clean up the extra errors/warnings so that the utilities are easier to digest for administrators who are typically just looking for certain information about what computations are running

**Comment by MikeNeilson** [comment]
Applications are behaving correctly in 7.0.13-RC02
