### ISSUE TITLE
The properties providers in LRGS data source - used by routine spec -  not working for me.

### ISSUE THREAD

**Issue by ktarbet** [opendcs/opendcs#687]
**Describe the bug**
The environment expansion doesn't seem to be working for a LRGS data source (password)

**To Reproduce**
* set username and password with new feature.
![image](https://github.com/user-attachments/assets/cbe011aa-c4be-4ed0-8305-2ab52247018f)

** what happended?
It appers the username worked ok, but not password.
```bash
DBG1    09/04/24 23:01:09 processDataSource for LrgsDataSource for 'cdadata', args='port=16003, hostname=cdadata.wcda.noaa.gov,
      password=$[env.CDADATA_PASSWORD}, username=${env.CDADATA_USERNAME}'
DBG1    09/04/24 23:01:09 DataSource 'cdadata' NOT Allowing DAPS Status Messages.
DBG1    09/04/24 23:01:09 DataSource 'cdadata'  allowNullPlatform set to false
DBG1    09/04/24 23:01:09 RoutingSpec(jck) rst.init: calling source init, there are 0 NLs, and 0 NL Names
DBG1    09/04/24 23:01:09 RoutingSpec(jck) LrgsDataSource.init() for 'cdadata' since='now -2 hour' until= 'now'
DBG3    09/04/24 23:01:09 RoutingSpec(jck) LrgsDataSource 'cdadata' host=cdadata.wcda.noaa.gov, host property = 'cdadata.wcda.noaa.gov'
WARNING 09/04/24 23:01:09 It appears that your password is saved directly in the property. This is not secure. It recommended that you migrate to one of the properties providers such as environment or secrets files.
DBG2    09/04/24 23:01:09 RoutingSpec(jck) LrgsDataSource.openConnection to host 'cdadata.wcda.noaa.gov', port=16003
DBG2    09/04/24 23:01:09 lrgsds-0 Connecting to 'cdadata.wcda.noaa.gov', port 16003
DBG2    09/04/24 23:01:09 lrgsds-0 DDS Connection (cdadata.wcda.noaa.gov:16003) sendAuthHello(**username HERE OK**)
DBG1    09/04/24 23:01:09 AuthHello response '?47,0,Bad password'
DBG2    09/04/24 23:01:09 lrgsds-0 Disconnecting from 'cdadata.wcda.noaa.gov', port 16003
DBG2    09/04/24 23:01:09 BasicClient cdadata.wcda.noaa.gov:16003 disconnect()
FAILURE 09/04/24 23:01:09 Cannot initialize data source 'cdadata
FAILURE 09/04/24 23:01:09 decodes.datasource.DataSourceException: Cannot connect to LRGS at 'cdadata.wcda.noaa.gov:16003, username='${env.CDADATA_USERNAME}': Server Error: Bad password (DDDSAUTHFAILED-47) DDS Authentication failed
	at decodes.datasource.LrgsDataSource.openConnection(LrgsDataSource.java:985)
	at decodes.datasource.LrgsDataSource.init(LrgsDataSource.java:324)
	at decodes.routing.RoutingSpecThread.init(RoutingSpecThread.java:1063)
	at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:264)

DBG1    09/04/24 23:01:09 ScheduleEntryExecutive.rsFinished() SchedEntry:jck-manual state is now shutdown
INFO    09/04/24 23:01:09 RoutingSpec(jck) -------------- RoutingSpec 'jck' Terminating --------------

```

**Expected behavior**
* The password should be expanded.

**Desktop
 - OS: Windows 11

**Comment by MikeNeilson** [comment]
the "real" password is expanded before the LRGS connection, See LrgsDataSource:949 and the value is used.

Are you sure the environment variable is set correctly and there's no typos in the name?

**Comment by ktarbet** [comment]
@MikeNeilson  Thanks for your help

The issue was the square bracket

password=$[env.CDADATA_PASSWORD}
