### ISSUE TITLE
Get 7.1 branch ivy dependencies working with CWMS DB

### ISSUE THREAD

**Issue by MikeNeilson** [opendcs/opendcs#70]
**Describe the bug**
That which access the CWMS database fails to connect to DB

**To Reproduce**
1. create build with ant opendcs
2. install with java -jar stage/opendcs-ot-7.1.0.jar
3. <config to connect to a CWMS database>
4. Attempt to login

**Expected behavior**
Login works

**Screenshots**

**Desktop/ServerSide (please complete the following information):**

```Init DECODES DB: Cannot connect to database: decodes.tsdb.BadConnectException: Cannot get CWMS connection for user 'q0hecman', officeId='SPK' and dbURI='jdbc:oracle:thin:@localhost:1521/CWMSDEV: java.sql.SQLException: No implementation lookup service available. No access to the database is available. Please check project configuration. Trying to use cwms.db.impl.classpaths path: /home/mike/opendcs-installs/7.1.0/cwmsDbAPI
decodes.tsdb.BadConnectException: Cannot get CWMS connection for user 'q0hecman', officeId='SPK' and dbURI='jdbc:oracle:thin:@localhost:1521/CWMSDEV: java.sql.SQLException: No implementation lookup service available. No access to the database is available. Please check project configuration. Trying to use cwms.db.impl.classpaths path: /home/mike/opendcs-installs/7.1.0/cwmsDbAPI
	at decodes.cwms.CwmsTimeSeriesDb.getDbConnection(CwmsTimeSeriesDb.java:802)
	at decodes.cwms.CwmsSqlDatabaseIO.connectToDatabase(CwmsSqlDatabaseIO.java:185)
	at decodes.cwms.CwmsSqlDatabaseIO.<init>(CwmsSqlDatabaseIO.java:85)
	at decodes.db.DatabaseIO.makeDatabaseIO(DatabaseIO.java:66)
	at lrgs.gui.DecodesInterface.initDecodesMinimal(DecodesInterface.java:207)
	at lrgs.gui.DecodesInterface.initDecodes(DecodesInterface.java:149)
	at decodes.launcher.LauncherFrame.doInitDecodes(LauncherFrame.java:1308)
	at decodes.launcher.LauncherFrame.access$1200(LauncherFrame.java:177)
	at decodes.launcher.LauncherFrame$36.run(LauncherFrame.java:1119)
Exception in thread "Thread-1" java.lang.NullPointerException
	at decodes.cwms.CwmsSqlDatabaseIO.connectToDatabase(CwmsSqlDatabaseIO.java:202)
	at decodes.cwms.CwmsSqlDatabaseIO.<init>(CwmsSqlDatabaseIO.java:85)
	at decodes.db.DatabaseIO.makeDatabaseIO(DatabaseIO.java:66)
	at lrgs.gui.DecodesInterface.initDecodesMinimal(DecodesInterface.java:207)
	at lrgs.gui.DecodesInterface.initDecodes(DecodesInterface.java:149)
	at decodes.launcher.LauncherFrame.doInitDecodes(LauncherFrame.java:1308)
	at decodes.launcher.LauncherFrame.access$1200(LauncherFrame.java:177)
	at decodes.launcher.LauncherFrame$36.run(LauncherFrame.java:1119)
```

**Additional context**
the dependencies are defined in ivy.xml and the classpaths are set in common.xml
branch https://github.com/opendcs/opendcs/tree/7.1

**Comment by MikeNeilson** [comment]
Finished by @adamkorynta with #72
