### ISSUE TITLE
New install of RC08 has DB Password button dbAuthFile problems

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#725]
**Describe the bug**
When starting with a blank install, going into setup, changing the Database Type to HDB, and clicking the DB Password button results in the following stack trace, and the password change dialog does not appear.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at decodes.launcher.DecodesPropsPanel.dbPasswordButtonPressed(DecodesPropsPanel.java:209)
        at decodes.launcher.DecodesPropsPanel.lambda$jbInit$1(DecodesPropsPanel.java:117)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It appears that the DBAuthFile setting isn't defaulting to something useful in a new installation.

**Expected behavior**
Clicking the DB Password button should allow changing the password as normal.

**Desktop/ServerSide (please complete the following information):**
 - OS: Windows 10
 - Version: 7.0.13-RC08 downloaded today

**Comment by MikeNeilson** [comment]
should default to `$DCSTOOL_USERDIR/.decodes.auth`. could be from a change I made to the props panel that I didn't catch.

**Comment by agilmore2** [comment]
sounds likely.

Workaround is supplying a known good decodes.properties file.

**Comment by MikeNeilson** [comment]
Looking at the code, there's no null check and that field is defaulted to null for an XML database (the default) and just changing to HDB doesn't add the value in. 

Given this bug has been there for a while just waiting to happen, not related to any changes, and needs to thought as to how to better handle it; I'm going to punt this until after .13 is released.
