### ISSUE TITLE
V7.0.13 client release,  "Java .ArrayIndexOutOfBoundsException" from GUI 

### ISSUE THREAD

**Issue by vwreck86** [opendcs/opendcs#765]
After installing the newest release client,  multiple users are receiving "java.ArrayIndexOutOfBoundsException"  when attempting to open  message browser and LRGS Status.  

```text
-------------------------------------
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at lrgs.rtstat.hosts.LrgsConnection.fromDdsFile(LrgsConnection.java:139)
        at lrgs.rtstat.hosts.LrgsConnectionComboBoxModel.<init>(LrgsConnectionComboBoxModel.java:55)
        at lrgs.rtstat.hosts.LrgsConnectionPanelController.<init>(LrgsConnectionPanelController.java:18)
        at lrgs.rtstat.hosts.LrgsConnectionPanel.<init>(LrgsConnectionPanel.java:59)
        at lrgs.gui.MessageBrowser.<init>(MessageBrowser.java:91)
        at decodes.launcher.LauncherFrame$34.run(LauncherFrame.java:887)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
-----------------------------------------------

**Comment by MikeNeilson** [comment]
It appears there's an issue in some error handling. We'll need the LddsConnection file (replace any actual passwords with the word `password`) to investigate further.

This file will be in your DCSTOOL_USERDIR location.

**Comment by ktarbet** [comment]
I think something higher level may need adjustment? 

I don't think comment lines are being filtered out?

 Here is an example file
```text
#Recent LRGS Connections
#Wed Sep 18 08:11:47 PDT 2024
server1=16003 admin 1234567890123 password-here---
server2.name.abc=16003 user2 1234567890123 password-here---
192.168.0.1=16003 anotheradmin 1234567890123 password-here---
```

The error appears to be caused by a parts[] array that has only one item.

```java
 public static LrgsConnection fromDdsFile(String host, String input)
    {
        final String parts[] = input.split("\\s+");
        final int port = Integer.parseInt(parts[0]);
        final String username = parts[1];
        final Long lastUsed = Long.parseLong(parts[2]);
        final String password = parts[3];

        return new LrgsConnection(host, port,
                                  username, password, new Date(lastUsed));
    }
```

code that may need a filter for comment lines?


``` java
 public LrgsConnectionComboBoxModel(File lddsConnectionFile)
    {
        this.lddsConnectionFile = lddsConnectionFile;
        hosts.add(LrgsConnection.BLANK);
        try (FileInputStream fis = new FileInputStream(lddsConnectionFile);)
        {
            Properties props = new Properties();
            props.load(fis);
            for (String key: props.stringPropertyNames())
            {
                hosts.add(LrgsConnection.fromDdsFile(key, props.getProperty(key)));
            }

```

**Comment by MikeNeilson** [comment]
`Properties::load` takes care of the comments. 
That said, I may not have tested without a password which could be part of the issue, though I thought I copy-pasted most of the logic, perhaps I tried to clean it up.

**Comment by ktarbet** [comment]
When I get the new gradle build working on windows I can work on this.

**Comment by ktarbet** [comment]
I've tested with both 7.0.13 and 7.0.14 and cannot reproduce this issue.  
@vwreck86  - I'll reach out to you directly.

**Comment by MikeNeilson** [comment]
This was fixed in #919. Issue was LddConnection files that only had the host entry.
The original code must have handled that correctly and adjustments were made to deal with and correct the situtation.

Fixed in https://github.com/opendcs/opendcs/releases/tag/7.0.15-RC02
