### ISSUE TITLE
7.0.14: Argument overflow when committing a Site change

### ISSUE THREAD

**Issue by agilmore2** [opendcs/opendcs#786]
**Describe the bug**
I get this backtrace when committing changes to Site records:

```
DBG3    11/06/24 01:12:01 LoadingAppDao Query1 'select LOADING_APPLICATION_ID, PROP_NAME, PROP_VALUE from REF_LOADING_APPLICATION_PROP '
INFO    11/06/24 01:12:12 UPDATE site SET latitude=?, longitude=?, nearestCity=?, state=?, region=?, timezone=?, country=?, elevation=?, elevunitabbr=?, description=?, active_flag=?, location_type=?, modify_time=?, public_name=?  WHERE id = ?
FAILURE 11/06/24 01:12:12 Unable to write site decodes.db.Site@7044283d.
FAILURE 11/06/24 01:12:12 java.lang.IllegalArgumentException: Overflow
        at oracle.jdbc.driver.OraclePreparedStatement.setDoubleInternal(OraclePreparedStatement.java:5157)
        at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:8367)
        at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:8065)
        at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:8852)
        at oracle.jdbc.driver.OraclePreparedStatement.setObject(OraclePreparedStatement.java:8832)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:219)
        at opendcs.dao.DaoBase.bind(DaoBase.java:525)
        at opendcs.dao.DaoBase.lambda$withStatement$1(DaoBase.java:447)
        at opendcs.dao.DaoBase.withConnection(DaoBase.java:420)
        at opendcs.dao.DaoBase.withStatement(DaoBase.java:440)
        at opendcs.dao.DaoBase.doModify(DaoBase.java:575)
        at opendcs.dao.SiteDAO.update(SiteDAO.java:522)
        at opendcs.dao.SiteDAO.writeSite(SiteDAO.java:443)
        at decodes.sql.SqlDatabaseIO.writeSite(SqlDatabaseIO.java:1168)
        at decodes.db.Site.write(Site.java:377)
        at decodes.dbeditor.SiteEditPanel.saveChanges(SiteEditPanel.java:578)
        at decodes.dbeditor.SiteEditPanel.commitEntity(SiteEditPanel.java:597)
        at decodes.dbeditor.EntityOpsPanel.commitButton_actionPerformed(EntityOpsPanel.java:75)
        at decodes.dbeditor.EntityOpsPanel$1.actionPerformed(EntityOpsPanel.java:45)
        at <...Swing trace for another 30 frames>
```

**To Reproduce**
Run dbedit
Make a change to a site
Click commit.

**Screenshots**

**Desktop/ServerSide (please complete the following information):**
 - OS: Fedora 39
 - Version 7.0.14

**Additional context**
Database Site table has the correct number of columns. Appears to be some type disagreement between parameter types?
Not sure how to determine which one of the parameters in the collection are errorring.

See attached GUI log.
[gui.log](https://github.com/user-attachments/files/17640441/gui.log)

**Comment by MikeNeilson** [comment]
`at oracle.jdbc.driver.OraclePreparedStatement.setDoubleInternal(OraclePreparedStatement.java:5157)`

Are your lat/long fields in the database sufficient to hold a binary_double?

If not you'll need to add an appropriate ifHdb check [hereish](https://github.com/opendcs/opendcs/blob/f8b25dfa5b706a85fc94cb7c4e335bb4c7cddd2e/java/opendcs/src/main/java/opendcs/dao/DaoBase.java#L521) and call other than setDouble as appropriate.

**Comment by agilmore2** [comment]
This is from BCHydro, not HDB. The Lat/Long fields are VARCHAR2(24 BYTE), and the elevation is an Oracle "FLOAT". MODIFY_TIME is a NUMBER(19,0). These all seem to match the table definition in schema/opendcs-oracle/opendcs.sql

**Comment by MikeNeilson** [comment]
whelp, that table definition is... unfortunate.

**Comment by agilmore2** [comment]
I'll ask, but I doubt it. :/

**Comment by MikeNeilson** [comment]
Mostly a joke, but perhaps worth a try anyways. In the mean time I was planning on getting the OpenDCS Oracle schema migrated over to flyway and available for integration tests. Bit easier to do now that Oracle has their "oracle-free" images on dockerhub.

I don't know if I'll have time to completely finish the work but if you're working with BCHydro it should help a lot in sorting those things out.

Likely won't start until tomorrow though, and I'll be on vacation all next week and not likely even working on hobby projects.

**Comment by agilmore2** [comment]
I need to investigate those oracle-free images for HDB testing!

It seemed to be immediately obvious to you which field is causing issues. Lat/Long may be a string if someone is using DMS notation though?

**Comment by MikeNeilson** [comment]
It's still partly a guess, based on the line number provided. To know for sure stepping through the code to determine the actual datatype and index would be needed - perhaps that block should be updated to be able to print the column index on error.

But we know that DMS notation can't be used for that field, `class Site` only includes lat/long as double, and I don't recall ever reading any code while changing the read or write of Site that converted the notation to such.

**Comment by MikeNeilson** [comment]
So it turns out it wasn't the varchar type that was the issue. It was the fact that the java constant for Double.MAX_VALUE is slightly higher than the binary_double of Oracle by like 3 or 4 digits. So because it was setting the value as a double, when it tried to do the conversion it fails. Double.MAX_VALUE happens to be the default value assigned to the site elevation since it's a primitive and not a `Double`

In #818 I tweaked tweaked the bind handler to just put null if the value is equal to Double.MAX_VALUE.

Still needs review and a merge, but can quickly get it into the 7.0 branch after that, or can just be tested from main as they are still close together.
