### ISSUE TITLE
[OpenDCS 6.5RC03] Postgres 15+ ConfigList Queries Failing

### ISSUE THREAD

**Issue by ghansen-bor-dp** [opendcs/opendcs#808]
**Describe the bug**
OpenDCS 6.5 is creating malformed config sensor SQL queries that Postgres 15+ versions no longer automatically resolve. After upgrading from Postgres 13 to 16, OpenDCS 6.5 started throwing the following error:

org.postgresql.util.PSQLException: ERROR: trailing junk after numeric literal at or near "423AND"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1608)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1343)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:194)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:336)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:235)
        at decodes.sql.ConfigListIO.readConfigSensors(ConfigListIO.java:253)
        at decodes.sql.ConfigListIO.putConfig(ConfigListIO.java:150)
        at decodes.sql.ConfigListIO.readConfig(ConfigListIO.java:333)
        at decodes.sql.SqlDatabaseIO.readConfig(SqlDatabaseIO.java:1370)
        at decodes.db.PlatformConfig.read(PlatformConfig.java:457)
        at decodes.sql.PlatformListIO.readPlatform(PlatformListIO.java:479)
        at decodes.sql.SqlDatabaseIO.readPlatform(SqlDatabaseIO.java:1211)
        at decodes.db.Platform.read(Platform.java:531)
        at decodes.db.PlatformList.getPlatform(PlatformList.java:152)
        at decodes.datasource.LrgsDataSource.lrgsMsg2RawMessage(LrgsDataSource.java:707)
        at decodes.datasource.LrgsDataSource.getRawMessage(LrgsDataSource.java:618)
        at decodes.routing.RoutingSpecThread.run(RoutingSpecThread.java:360)
        
 I believe the PSQLException is being caused by this malformation in the query:
 https://github.com/opendcs/opendcs/blob/OPENDCS65_RC03/src/decodes/sql/ConfigListIO.java#L253
           + "WHERE ConfigId = " + platformConfigId
          + "AND ConfigSensorDataType.dataTypeId = DataType.id");
Queries are being produced that look like this for us:
WHERE ConfigId = ...432AND ConfigSensorDataType.dataTypeId = DataType.id

Prior to version 15, Postgres would automatically separate the AND token from the numeric literal in front of it, which was unintended behavior: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=2549f0661

This unintended behavior just happened to fix the queries on older Postgres versions, resulting in the following:
WHERE ConfigId = ...432 AND ConfigSensorDataType.dataTypeId = DataType.id

We need a space added before the AND token to fix the problem: " AND ConfigSensorDataType.dataTypeId = DataType.id");

**To Reproduce**
1. Configure an OpenDCS 6.5RC03 instance to point to a Postgres 15/16 database.
2. Run any routing spec at a high diagnostic level: decodes.routing.RoutingSpecThread -d 5 -l test.log <RS>
3. Observe the above stack trace appearing in the logfile, the routing spec fails.

**Expected behavior**
Properly formed SQL queries should be made to the ConfigSensorDataType table in supported OpenDCS versions.

**ServerSide:**
 - OS: RHEL 9.0
 - Database: Postgres 16

**Comment by MikeNeilson** [comment]
Well, we're definitely not going to fix 6.5, but we'll check 6.8 and recent version to see if that bug is still there.

**Comment by MikeNeilson** [comment]
Okay, still exists in 6.8.14, was fixed in 7.0.8.

**Comment by MikeNeilson** [comment]
@DanielTOsborne exactly how many fixes did you say you have for 6.8?

The build is not function, just checked, so would be some work to get running again, trying to decide if it's worth making a 6.8.15 or not.

**Comment by MikeNeilson** [comment]
Given no response from @DanielTOsborne I'm closing this as won't fix for 6.8 or below.
If there are more people requesting this or other fixes we can revisit the decision; however, at the moment were somewhat overloaded with larger database usage correction efforts.
