### ISSUE TITLE
Bug in new lambda code for reading DECODES Enumerations

### ISSUE THREAD

**Issue by mikecovesw** [opendcs/opendcs#97]
**Describe the bug**
Under 7.0.2 compiled from master on 9/9/2022, showCompDepends gives the following error:

Cannot read enum: SiteNameType: decodes.db.DatabaseException: decodes.tsdb.DbIoException: Error in query 'SELECT id, name, defaultValue, description  FROM Enum where lower(name) = lower(?)': org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of decodes.sql.DbKey. Use setObject() with an explicit Types value to specify the type to use.
decodes.db.DatabaseException: decodes.tsdb.DbIoException: Error in query 'SELECT id, name, defaultValue, description  FROM Enum where lower(name) = lower(?)': org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of decodes.sql.DbKey. Use setObject() with an explicit Types value to specify the type to use.
	at decodes.sql.SqlDatabaseIO.readEnum(SqlDatabaseIO.java:645)
	at decodes.db.Database.getDbEnum(Database.java:246)
	at decodes.db.SiteList.getNameTypeEnumValue(SiteList.java:103)
	at decodes.db.SiteName.getNameTypeEnumValue(SiteName.java:111)
	at decodes.db.SiteName.<init>(SiteName.java:76)
	at decodes.db.SiteName.<init>(SiteName.java:96)
	at opendcs.dao.SiteDAO.fillCache(SiteDAO.java:342)
	at opendcs.dao.SiteDAO.read(SiteDAO.java:380)
	at decodes.sql.SqlDatabaseIO.readSiteList(SqlDatabaseIO.java:740)
	at decodes.db.SiteList.read(SiteList.java:215)
	at decodes.tsdb.CompDependsList.initDecodes(CompDependsList.java:143)
	at decodes.tsdb.TsdbAppTemplate.execute(TsdbAppTemplate.java:225)
	at decodes.tsdb.CompDependsList.main(CompDependsList.java:48)

It looks like the new lambda-based code is failing to define the ? parameter before executing the SQL.

**To Reproduce**
1. Go to any system where there are computations defined. Open shell window.
2. Type "showCompDepends"
3. 
4. See stderr with the stack trace (above). The program does appear to complete in spite of the error.

I see this for both CWMS on the RMA test server and for OpenTSDB under postgres.

**Additional context**
There are probably other places in the code where decodes.db.getDbEnum is called that will elicit the same error.

**Comment by MikeNeilson** [comment]
Haha. the error is actually on Line 293 in EnumSqlDao.java, it just got a little buried. That's why I modified the exception to take the previously through exception, helps with the stacktraces, but I hadn't gotten to all of them.

The best solution is to have DbKey implement SQLDatatype, but the easiest to it just put an instanceof handler in. I'll do that now and work on the "better" fix later.
